(ns audio-platform.screens.player
  (:require
   ["package:flutter/material.dart" :as m]
   ["package:mongol/mongol.dart" :as mgl]
   [cljd.flutter :as f]
   [audio-platform.state :as state]
   [audio-platform.services.audio-player :as audio-player]
   [audio-platform.utils.format :as format]
   [audio-platform.widgets.common :as common]
   [audio-platform.widgets.player :as player-widget]))

(defn player-page []
  (player-widget/player-widget))
